descope/descope-js

- packages/web-component/README.md
- packages/web-js-sdk/README.md
> chore: Readme enhancements

- LICENSE
add license to the monorepo repo root level, this is commonly done and improve license for readers visibility
> Chore: add license 

- packages/core-js-sdk/src/sdk/oauth/index.ts
- packages/core-js-sdk/src/sdk/oauth/types.ts
- packages/core-js-sdk/test/sdk/oauth.test.ts
- packages/web-js-sdk/examples/oauth/index.html
> fix: remove oauth redirect

- packages/core-js-sdk/src/sdk/types.ts
> fix: Export user created time in user response

- packages/core-js-sdk/src/sdk/types.ts
- packages/web-component/src/lib/constants/index.ts
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/helpers.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
- packages/web-js-sdk/src/sdk/flow.ts
Add the ability to pass OIDC url param ("stateId") into the flow.
> feat: add oidc flow start param

- packages/core-js-sdk/src/sdk/types.ts
related to https://github.com/descope/etc/issues/2640
> feat: totp, saml and oauth are now on user directly

- packages/core-js-sdk/src/sdk/types.ts
- packages/web-component/src/lib/constants/index.ts
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/helpers.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
- packages/web-js-sdk/src/sdk/flow.ts
This reverts commit 44248e3ca7d5f4aaf1dc50e7f369d03a98a55d73.
Related to https://github.com/descope/etc/issues/949
> Revert feat: add oidc flow start param (#120)

- packages/core-js-sdk/src/httpClient/index.ts
- packages/core-js-sdk/src/httpClient/types.ts
- packages/core-js-sdk/test/httpClient.test.ts
> fix:Http delete should be called without a body

- packages/core-js-sdk/package.json
- packages/web-js-sdk/package.json
- pnpm-lock.yaml
related: https://github.com/descope/etc/issues/2768
> fix: add types to package.json#exports RELEASE

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/helpers.ts
- packages/web-component/test/descope-wc.test.ts
When OIDC flow is on - we don't want to apply the start optimization
> fix: Skip start optimization fro oidc flows

- packages/core-js-sdk/test/sdk/oauth.test.ts
- packages/core-js-sdk/test/sdk/saml.test.ts
small remaining from previous PR
> chore: remove window from tests

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/test/descope-wc.test.ts
Fixes https://github.com/descope/etc/issues/2896
Stopped working after some changes for OIDC, we need to start thinking of how to refactor this area so it won't be so fragile
@nirgur
> fix: send last auth always on start

- packages/web-component/src/lib/helpers/templates.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/helpers/templates.test.ts
https://github.com/descope/etc/issues/2857#issuecomment-1582366527
support form attribute that should replace inputs
> chore: support form attribute 

- packages/web-js-sdk/src/enhancers/helpers/logger.ts
- packages/web-js-sdk/src/enhancers/withAutoRefresh/index.ts
- packages/web-js-sdk/test/autoRefresh.test.ts
https://github.com/descope/etc/issues/2869
Added a naive logger for auto-refresh actions in debug level
this may help us find root cause of refresh issues, lmk what you think
> chore: Add logger

- packages/web-js-sdk/src/index.ts
- packages/web-js-sdk/test/sdk.test.ts
expose session/refresh token constant 
this is requested from developer in Descope community
> feat: expose tokens constants

- packages/web-js-sdk/README.md
https://github.com/descope/etc/issues/3105
improve readme to note about `sessionTokenViaCookie`
> chore: Improve docs

- packages/web-component/README.md
- packages/web-component/src/app/index.html
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/templates.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
Related https://github.com/descope/etc/issues/3022
@nirgur please LMK what you think of this code, still missing tests
> feat: Add an option to translate end user errors

- packages/core-js-sdk/package.json
- packages/core-js-sdk/src/sdk/enchantedLink/index.ts
- packages/web-component/package.json
- pnpm-lock.yaml
remove unused `eslint-plugin-jsx-a11y`
> chore: Remove unused pacakge

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/test/descope-wc.test.ts
This way we can have a flow that will start with verify token 
related to https://github.com/descope/etc/issues/2288
> feat: Fetch token from url on start

- packages/web-component/README.md
- packages/web-component/rollup.config.app.js
- packages/web-component/src/app/index.html
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/test/descope-wc.test.ts
https://github.com/descope/etc/issues/290
Flow config locales usage
> feat: flow config locales usage

- packages/core-js-sdk/src/sdk/types.ts
- packages/web-component/README.md
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/descope-wc/index.ts
- packages/web-component/src/lib/helpers/helpers.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/debugger.test.ts
- packages/web-component/test/descope-wc.test.ts
- packages/web-component/test/testUtils.ts
related https://github.com/descope/etc/issues/2892
react sdk - https://github.com/descope/react-sdk/pull/380
app - 
- add `onNext` event on web component to callback on next action including action details and state
- move logger to function to allow overloading
- add trycatch to screen html file
- add step name to flow responses
> feat: Add logger prop for runner

- packages/web-component/README.md
> chore: Translate translation for error transformer

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/conditions.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
related to https://github.com/descope/etc/issues/3888
> feat: Add client side condition for embedded/invite token

- packages/core-js-sdk/src/sdk/types.ts
- packages/web-js-sdk/src/sdk/flow.ts
- packages/web-js-sdk/test/sdk.test.ts
https://github.com/descope/etc/issues/3786
separate location into a different url 
need to merge this after Descope service supports this
> feat: separate redirect url and location

- packages/core-js-sdk/src/sdk/flow/index.ts
- packages/core-js-sdk/test/sdk/flow.test.ts
- packages/web-component/jest.config.js
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
- packages/web-component/test/webauthnConditionalUi.test.ts
Fixes https://github.com/descope/etc/issues/3680
> Pass components v2 in flow calls

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/test/descope-wc.test.ts
- pnpm-lock.yaml
Take the first part of local, so `es-MX` will be `es`.
Exception is `zh-TW`
> feat: Take the first part of locale

- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
Related https://github.com/descope/etc/issues/3733
> Components context

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/helpers.ts
- packages/web-component/test/descope-wc.test.ts
Related: https://github.com/descope/web-components-ui/pull/158
> Support UploadFileV2

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
Fixes https://github.com/descope/etc/issues/4251
- Cleanup conditional login request when web-component is removed
> fix: Abort conditional login when component is removed

- packages/core-js-sdk/src/sdk/types.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/abTestingKey.ts
- packages/web-component/src/lib/helpers/conditions.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
- packages/web-js-sdk/src/sdk/flow.ts
Also now we know how to handle predicates in conditions
+ tests
fixes https://github.com/descope/etc/issues/2333
> feat: AB testing client condition calculation

- packages/core-js-sdk/src/constants/apiPaths.ts
- packages/core-js-sdk/src/sdk/index.ts
- packages/core-js-sdk/test/sdk/sdk.test.ts
- pnpm-lock.yaml
+tests
related to https://github.com/descope/etc/issues/3078 Added an API call for selecting a tenant and placing it on the jwt as a custom claim
> feat: Select tenant

- packages/core-js-sdk/src/sdk/types.ts
https://github.com/descope/etc/issues/4672
Add `status` to the user response
> feat: Add `status` to the user response RELEASE

- .gitignore
- package.json
- pnpm-lock.yaml
> chore: Fix ci RELEASE

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
fixes: https://github.com/descope/etc/issues/4743
> fix: issue 4743 RELEASE

- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
Related https://github.com/descope/etc/issues/4762
> fix: issue 4762 RELEASE

- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/test/testUtils.ts
Fixes https://github.com/descope/etc/issues/4817
> fix: issue 4817 RELEASE

- packages/core-js-sdk/src/sdk/types.ts
- pnpm-lock.yaml
related to https://github.com/descope/etc/issues/4501
> feat: Given/Family name support

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/index.ts
- packages/web-component/src/lib/helpers/templates.ts
- packages/web-component/test/helpers/templates.test.ts
Related https://github.com/descope/etc/issues/4877
> fix: issue 4877 RELEASE

- packages/core-js-sdk/src/sdk/index.ts
adding some top level docs for our top level functions, other functions may need as well but I found those less trivial and simpler to doc (according to go-sdk docs)
> chore: add some docs

- packages/core-js-sdk/src/sdk/index.ts
- packages/web-component/src/lib/constants/index.ts
- packages/web-component/src/lib/helpers/templates.ts
- packages/web-component/test/descope-wc.test.ts
- pnpm-lock.yaml
related: https://github.com/descope/etc/issues/3405
> feat: support dynamic attribute values RELEASE

- packages/web-component/src/lib/constants/content.ts
- packages/web-component/src/lib/constants/general.ts
- packages/web-component/src/lib/constants/index.ts
- packages/web-component/src/lib/constants/uiComponents.ts
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/test/descope-wc.test.ts
fixes https://github.com/descope/etc/issues/4907
> fix: issue 4907 RELEASE

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/helpers.ts
- packages/web-component/test/descope-wc.test.ts
fixes https://github.com/descope/etc/issues/4430
1password:
https://github.com/descope/descope-js/assets/11805663/fe5ea2c2-99cf-47ce-9f8a-56f643c2cb1f
Safari:
https://github.com/descope/descope-js/assets/11805663/a1a0eb47-7d5e-4b13-98b6-1adaaca35b27
Chrome:
https://github.com/descope/descope-js/assets/11805663/1bef9a0c-9899-41e9-96a7-837e2c311252
> feat: support password managers RELEASE

- packages/core-js-sdk/src/sdk/types.ts
Add embedded delivery method
https://github.com/descope/etc/issues/5082
> feat: Add embedded delivery method

- packages/core-js-sdk/src/constants/index.ts
- packages/core-js-sdk/src/httpClient/index.ts
- packages/core-js-sdk/src/httpClient/urlBuilder.ts
- packages/core-js-sdk/test/httpClient.test.ts
Fixes https://github.com/descope/etc/issues/5120
> feat: Extract region from project ID

- packages/core-js-sdk/src/sdk/types.ts
- packages/web-component/src/lib/constants/index.ts
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/helpers.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
- packages/web-js-sdk/src/sdk/flow.ts
Fixes https://github.com/descope/descope-js/pull/349
> feat: support oidc login hint

- packages/core-js-sdk/src/sdk/enchantedLink/index.ts
- packages/core-js-sdk/src/sdk/magicLink/index.ts
- packages/core-js-sdk/src/sdk/magicLink/types.ts
- packages/core-js-sdk/src/sdk/otp/index.ts
- packages/core-js-sdk/src/sdk/password/index.ts
- packages/core-js-sdk/src/sdk/types.ts
- packages/core-js-sdk/test/sdk/enchantedLink.test.ts
- packages/core-js-sdk/test/sdk/magicLink.test.ts
- packages/core-js-sdk/test/sdk/otp.test.ts
- packages/core-js-sdk/test/sdk/password.test.ts
- pnpm-lock.yaml
Related to: https://github.com/descope/etc/issues/5196
Add the ability to pass template options to the sign up and update methods
> feat: Add the ability to pass template options to the sign up and update methods

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/test/descope-wc.test.ts
Reverts descope/descope-js#340
fixes: https://github.com/descope/etc/issues/5425
> Revert "fix: change polling to timeout" RELEASE

- packages/user-management-widget/e2e/user-management-widget.spec.ts
- packages/user-management-widget/package.json
- packages/user-management-widget/src/lib/index.ts
- packages/user-management-widget/src/lib/mixins/initElementMixin.ts
- packages/user-management-widget/src/lib/widget/drivers/gridDrivers/GridCustomColumnDriver.ts
- packages/user-management-widget/src/lib/widget/drivers/gridDrivers/GridDriver.ts
- packages/user-management-widget/src/lib/widget/index.ts
- packages/user-management-widget/src/lib/widget/mockTemplates/widgetTemplate.ts
- packages/user-management-widget/src/lib/widget/state/constants.ts
- packages/user-management-widget/src/lib/widget/state/selectors.ts
- pnpm-lock.yaml
related https://github.com/descope/etc/issues/4634
> fix: UMW fixes RELEASE

- packages/web-component/README.md
- packages/web-component/src/app/index.html
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/conditions.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
https://github.com/descope/etc/issues/4136
Add ready event with so developer-user can listen and show loading / any other purpose
> feat: Add page-updated event

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/test/webauthnConditionalUi.test.ts
https://github.com/descope/etc/issues/5557
Downgrade WebAuthn conditional UI failure to warning
> fix: Warn on WebAuthn conditional UI failure

- packages/user-management-widget/src/lib/widget/mixins/fetchWidgetPagesMixin.ts
- packages/user-management-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initCreateUserModalMixin.ts
- packages/user-management-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initDeleteUsersModalMixin.ts
Few fixes and temp fixes on top of https://github.com/descope/descope-js/pull/382
> fix: Widget pages from s3 - with temp changes

- packages/user-management-widget/src/lib/widget/mixins/fetchWidgetPagesMixin.ts
related https://github.com/descope/etc/issues/2127
https://github.com/descope/descope-js/pull/382
- modify widget screen url to contain widget type
> fix: widget screen url RELEASE

- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/test/descope-wc.test.ts
- pnpm-lock.yaml
If this button is marked aith auto-submit true
Maintain backward compatability to single button on page 
related to https://github.com/descope/etc/issues/1547
+ test
> fix: Auto submit upon enter

- packages/user-management-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initCreateUserRoleMultiSelectMixin.ts
> fix: Pass function to MultiSelect driver constructor RELEASE

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/test/descope-wc.test.ts
- packages/web-js-sdk/src/enhancers/withFingerprint/constants.ts
- packages/web-js-sdk/src/enhancers/withFingerprint/helpers.ts
Related to https://github.com/descope/etc/issues/5367
Support fingerprinting with custom domain
> chore: fingerprinting with custom domain

- .github/workflows/ci.yml
- packages/access-key-management-widget/playwright.config.ts
- packages/role-management-widget/playwright.config.ts
- packages/user-management-widget/playwright.config.ts
> chore: github report for e2e

- packages/core-js-sdk/package.json
- packages/core-js-sdk/src/sdk/validations/validators.ts
- packages/libs/sdk-component-drivers/package.json
- packages/libs/sdk-helpers/package.json
- packages/libs/sdk-mixins/package.json
- packages/web-js-sdk/package.json
- pnpm-lock.yaml
https://github.com/descope/etc/issues/5940
replace lodash get with [the following impelmentation](https://gist.github.com/dfkaye/59263b51cf1e0b633181c5f44ae2066a) so package may run on various 
tested web-component sample app
and also web-js sample app
> fix: polyfil lodash get

- packages/libs/sdk-mixins/src/mixins/initElementMixin.ts
> fix: change style so notifications will be displayed inside the widget

- packages/web-component/package.json
- packages/web-component/rollup.config.mjs
- pnpm-lock.yaml
> chore: RELEASE

- packages/web-component/src/lib/constants/index.ts
https://github.com/descope/etc/issues/6032
> fix: Do not submit form when textarea focused RELEASE

- packages/access-key-management-widget/test/mocks/rootMock.ts
- packages/libs/sdk-mixins/src/mixins/themeMixin/themeMixin.ts
- packages/role-management-widget/test/mocks/rootMock.ts
- packages/user-management-widget/test/mocks/rootMock.ts
> fix: widget fixes RELEASE

- packages/access-key-management-widget/src/lib/widget/api/sdk/mocks.ts
- packages/role-management-widget/src/lib/widget/api/sdk/mocks.ts
- packages/user-management-widget/src/lib/widget/api/sdk/mocks.ts
> fix: 9 items in widgets search mocks RELEASE

- packages/core-js-sdk/src/sdk/magicLink/index.ts
- packages/core-js-sdk/src/sdk/types.ts
- packages/core-js-sdk/test/sdk/otp.test.ts
https://github.com/descope/etc/issues/2668
OTP voice support
> feat: OTP voice support RELEASE

- .github/workflows/pull_request.yml
> chore: fix prefix for pr title

- packages/libs/sdk-component-drivers/src/gridDrivers/GridDriver.ts
- packages/libs/sdk-mixins/src/mixins/createValidateAttributesMixin/commonValidators.ts
Related: https://github.com/descope/etc/issues/6179
> fix: issue 6179 RELEASE

- packages/core-js-sdk/src/sdk/types.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/types.ts
- packages/web-component/test/descope-wc.test.ts
- packages/web-component/test/testUtils.ts
https://github.com/descope/etc/issues/2151
support opening a URL in a new tab
> feat: add open in a new tab

- packages/user-profile-widget/test/mocks/rootMock.ts
> chore: update UPW root mock RELEASE

- packages/user-profile-widget/src/lib/widget/api/sdk/index.ts
- packages/user-profile-widget/src/lib/widget/state/asyncActions/logout.ts
> fix: UPW - fix logout in mock mode RELEASE

- packages/user-profile-widget/src/lib/widget/mixins/flowRedirectUrlMixin.ts
- packages/user-profile-widget/src/lib/widget/mixins/helpers.ts
- packages/user-profile-widget/src/lib/widget/mixins/initMixin/initMixin.ts
> fix: UPW_redirect_flow RELEASE

- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/initTemplate.ts
- pnpm-lock.yaml
Fixes https://github.com/descope/etc/issues/6494
> fix: issue 6494

- packages/core-js-sdk/src/sdk/password/index.ts
- packages/core-js-sdk/test/sdk/password.test.ts
https://github.com/descope/etc/issues/6382
Add loginOptions to password sign in.
> feat: Add loginOptions to password sign in

- packages/core-js-sdk/src/sdk/password/index.ts
- packages/core-js-sdk/test/sdk/password.test.ts
https://github.com/descope/etc/issues/6382
Add sign up options to password sign up
> feat: Add sign up options to password sign up

- packages/web-component/src/lib/constants/content.ts
- packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/helpers.ts
- packages/web-component/test/descope-wc.test.ts
Fixes https://github.com/descope/etc/issues/6022
> feat: use base url for static content

- packages/access-key-management-widget/src/lib/widget/mixins/apiMixin.ts
- packages/audit-management-widget/src/lib/widget/mixins/apiMixin.ts
- packages/libs/sdk-mixins/src/index.ts
- packages/libs/sdk-mixins/src/mixins/baseUrlMixin.ts
- packages/libs/sdk-mixins/src/mixins/staticResourcesMixin/constants.ts
- packages/libs/sdk-mixins/src/mixins/staticResourcesMixin/staticResourcesMixin.ts
- packages/role-management-widget/src/lib/widget/mixins/apiMixin.ts
- packages/user-management-widget/src/lib/widget/mixins/apiMixin.ts
Related https://github.com/descope/etc/issues/6022
> fix: use base url for static content in widgets RELEASE

- packages/web-component/src/lib/descope-wc/initTemplate.ts
Fixes https://github.com/descope/etc/issues/6600
> fix: issue 6600 RELEASE

- packages/web-component/src/lib/helpers/templates.ts
Related https://github.com/descope/etc/issues/6618
> feat: Replace dynamic values on code snippet RELEASE

- packages/web-component/README.md
- packages/web-component/package.json
- packages/web-component/rollup.config.app.mjs
- packages/web-component/src/app-web-sample/index.html
- packages/web-component/src/app-web-sample/index.js
- pnpm-lock.yaml
add sample app that contains a bit more than the flow
this is helpful
- communicating developers basic usage
- testing changes in web-sdk and how they affect flows without the need for complex work
> chore: add app with web-sdk-demo-app

- packages/user-management-widget/e2e/user-management-widget.spec.ts
- packages/user-management-widget/src/lib/widget/state/selectors.ts
fixes: https://github.com/descope/etc/issues/6686
> fix: Allow to delete not editable user

- packages/core-js-sdk/src/httpClient/index.ts
- packages/core-js-sdk/src/httpClient/types.ts
- packages/core-js-sdk/test/utils.ts
Related https://github.com/descope/etc/issues/2182
> feat: HTTP Client buildUrl function RELEASE

- packages/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/web-component/src/lib/helpers/templates.ts
- packages/web-component/test/descope-wc.test.ts
- pnpm-lock.yaml
fixes https://github.com/descope/etc/issues/6799
> feat: Dynamic href RELEASE

- packages/user-profile-widget/package.json
- pnpm-lock.yaml
Fixes https://github.com/descope/descope-js/issues/641
> fix: issue 641 RELEASE

- packages/core-js-sdk/src/sdk/types.ts
- packages/web-component/src/lib/descope-wc/DescopeWc.ts
related to https://github.com/descope/etc/issues/6880
> feat: Log flow runner logs if they exists

- packages/access-key-management-widget/e2e/access-key-management-widget.spec.ts
> test: trying to stabilize AKM e2e

- packages/core-js-sdk/src/httpClient/index.ts
- packages/core-js-sdk/src/httpClient/types.ts
- packages/core-js-sdk/test/utils.ts
Adds support for the Patch method to the HTTP client
> feat: Add Patch method to HTTP client

- .github/workflows/ci.yml
- .github/workflows/release.yml
seems to cause due to an issue with action https://github.com/pnpm/pnpm/issues/6424#issuecomment-2208425416
> chore: bump pnpm action to v4

- packages/web-js-sdk/src/enhancers/withPersistTokens/index.ts
- packages/web-js-sdk/test/persistTokens.test.ts
remove console warn similar to how it was done in https://github.com/descope/descope-js/pull/674
> fix: remove console-warn

- packages/sdks/web-component/src/lib/helpers/flowInputs.ts
- packages/sdks/web-component/test/descope-wc.test.ts
+ test
fixes https://github.com/descope/etc/issues/5861
> fix: form.displayName to populate properly

- packages/sdks/react-sdk/examples/app/index.tsx
- packages/sdks/react-sdk/package.json
- packages/sdks/react-sdk/rollup.config.mjs
- packages/sdks/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
- pnpm-lock.yaml
Fixes https://github.com/descope/etc/issues/7075
Fix state initialization to avoid the base state overriding the WC state
> fix: Move deferredRedirect initialization to WC from base

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Reverts descope/descope-js#743
> fix: Revert "fix: polling timeout when click is response t triggers another polling"

- pnpm-lock.yaml
> fix: revert pnpm.lock

- packages/sdks/vue-sdk/package.json
> fix: Update package.json RELEASE

- nx.json
feat(nx-cloud): setup nx cloud workspace 
This commit set up Nx Cloud for your Nx workspace enabling distributed caching
and GitHub integration for fast CI and improved Developer Experience.
You can access your Nx Cloud workspace by going to 
https://cloud.nx.app/orgs/669fc79a87d71c8645c97496/workspaces/669fc7a9db75a0706be2b31b
**Note:** This commit attempts to maintain formatting of the nx.json, however you may need to correct formatting by running an nx format command and committing the changes.
> chore(nx-cloud): setup nx workspace

- .github/workflows/ci.yml
- packages/sdks/react-sdk/package.json
- pnpm-lock.yaml
> chore: Basic nx cloud CI

- nx.json
- packages/sdks/web-component/src/app/index.html
- packages/sdks/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Fixes https://github.com/descope/etc/issues/7166
Verified the scenario in the issue, 
In this case there is no response because there is no network so no error event will be dispatched,
Also added a default error object in case we did not get one from the server with the default values
> fix: issue 7166 RELEASE

- .github/workflows/release.yml
Release filed due to an old pnpm version
> chore: Update release.yml RELEASE

- .github/workflows/ci.yml
- .github/workflows/release.yml
- nx.json
replacing nx.json token to read-only and adding an rw token to env via secret
also adding missing env vars in release yaml
> fix(ci): token and missing env vars

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Related https://github.com/descope/etc/issues/7076
| WCUI | [Link to PR](https://github.com/descope/web-components-ui/pull/394) |
Remove `handleExternalInputs` from DescopeWC.
> chore: Remove external inputs support

- packages/sdks/nextjs-sdk/src/shared/index.ts
- packages/sdks/react-sdk/src/sdk.ts
- packages/sdks/vue-sdk/src/sdk.ts
Fixes https://github.com/descope/etc/issues/7219
> fix: issue 7219 RELEASE

- packages/libs/sdk-component-drivers/package.json
- packages/libs/sdk-component-drivers/src/gridDrivers/GridDriver.ts
- packages/libs/sdk-component-drivers/tsconfig.json
- packages/libs/sdk-helpers/package.json
- packages/libs/sdk-helpers/tsconfig.json
- packages/libs/sdk-mixins/package.json
- packages/libs/sdk-mixins/tsconfig.json
- packages/sdks/core-js-sdk/package.json
- packages/sdks/nextjs-sdk/CHANGELOG.md
- packages/sdks/nextjs-sdk/package.json
- packages/sdks/react-sdk/.eslintrc
- packages/sdks/react-sdk/package.json
- packages/sdks/react-sdk/src/types.ts
- packages/sdks/react-sdk/tsconfig.json
- packages/sdks/vue-sdk/package.json
- packages/sdks/web-component/package.json
- packages/sdks/web-js-sdk/package.json
- packages/sdks/web-js-sdk/tsconfig.json
- packages/widgets/access-key-management-widget/package.json
- packages/widgets/audit-management-widget/package.json
- packages/widgets/role-management-widget/package.json
- packages/widgets/user-management-widget/package.json
- packages/widgets/user-profile-widget/package.json
- packages/widgets/user-profile-widget/tsconfig.json
- pnpm-lock.yaml
Fixes https://github.com/descope/etc/issues/6274
> fix: Issue6274 RELEASE

- packages/sdks/nextjs-sdk/test/server/authMiddleware.test.ts
Bump version of the SDK and release the privateRoute support feature.
> chore: Release privateRoutes support and bump version

- packages/libs/sdk-mixins/src/mixins/baseStaticUrlMixin.ts
- packages/libs/sdk-mixins/src/mixins/baseUrlMixin.ts
- packages/sdks/web-component/test/descope-wc.test.ts
Fixes https://github.com/descope/etc/issues/7394
> fix: issue 7394 RELEASE

- packages/sdks/web-component/rollup.config.mjs
Fixes https://github.com/descope/etc/issues/7402
> fix: issue 7402 RELEASE

- packages/sdks/nextjs-sdk/package.json
- pnpm-lock.yaml
Fixes https://github.com/descope/etc/issues/7532
> fix: issue 7532 RELEASE

- packages/sdks/core-js-sdk/package.json
- packages/sdks/core-js-sdk/src/sdk/helpers/index.ts
- packages/sdks/core-js-sdk/test/sdk/helpers.test.ts
- packages/sdks/core-js-sdk/test/sdk/sdk.test.ts
- packages/sdks/web-js-sdk/package.json
- packages/sdks/web-js-sdk/src/enhancers/withAutoRefresh/helpers.ts
- packages/sdks/web-js-sdk/test/autoRefresh.test.ts
- pnpm-lock.yaml
fixes https://github.com/descope/etc/issues/7559
upgrade jwt decode to 4.0.0
> fix: upgrade jwt decode to 4.0.0.

- packages/sdks/react-sdk/src/components/Descope.tsx
- packages/sdks/react-sdk/src/types.ts
- packages/sdks/react-sdk/test/components/Descope.test.tsx
fix store last auth user prop in React SDK
in vue/angular it works well
> fix: store last auth user prop in React SDK

- packages/sdks/react-sdk/README.md
> fix: Update indentation in README.md

- packages/sdks/react-sdk/tsconfig.json
Fixes https://github.com/descope/etc/issues/6274
> fix: issue 6274 RELEASE

- .github/workflows/release-next.yml
related https://github.com/descope/descope-js/pull/786
> chore: only run if react sdk change

- .github/workflows/release-next-react-sdk.yml
fix release if not needed + rename in https://github.com/descope/descope-js/actions/workflows/release-next.yml
https://github.com/descope/descope-js/pull/797
related https://github.com/descope/etc/issues/4454
> chore: Fix next release if not needed

- packages/sdks/web-component/src/lib/helpers/helpers.ts
- packages/sdks/web-component/test/descope-wc.test.ts
Fixes https://github.com/descope/etc/issues/7744
Retain redirect auth URL params to maintain "mobile" state of the flow even if flow refreshes
> feat: Retain redirect auth URL params

- .gitignore
- packages/sdks/vue-sdk/README.md
- packages/sdks/vue-sdk/src/Descope.vue
- packages/sdks/vue-sdk/tests/Descope.test.ts
- packages/sdks/web-component/src/lib/descope-wc/index.ts
- packages/sdks/web-component/src/lib/types.ts
related to https://github.com/descope/etc/issues/7827
fixes https://github.com/descope/descope-js/issues/811
fixes https://github.com/descope/descope-js/issues/810
fixes https://github.com/descope/descope-js/issues/812
- change logger interface to be more loose ➰ 
- fix vue sdk readme based on a feedback 👍 
- add style id to vue sdk
> fix: logger typing improvements

- packages/widgets/applications-portal-widget/src/lib/widget/api/sdk/mocks.ts
Fixes https://github.com/descope/etc/issues/8042
> fix: issue 8042 RELEASE

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Fixes https://github.com/descope/etc/issues/8063
> fix: Fix updateScreenFromScreenState RELEASE

- packages/libs/escape-markdown/src/escapeMarkdown.ts
- packages/libs/escape-markdown/test/escapeMarkdown.test.ts
> chore: escpapeMarkdown fixes RELEASE

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
https://github.com/descope/etc/issues/5992
Add two more native options
- magicLinkRedirect
- ssoRedirect
> feat: Add more options to native options

- packages/sdks/angular-sdk/README.md
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/access-key-management/access-key-management.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/applications-portal/applications-portal.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/audit-management/audit-management.component.spec.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/audit-management/audit-management.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/descope/descope.component.spec.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/descope/descope.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/role-management/role-management.component.spec.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/role-management/role-management.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-in-flow/sign-in-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-in-flow/sign-in-flow.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-flow/sign-up-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-flow/sign-up-flow.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-or-in-flow/sign-up-or-in-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-or-in-flow/sign-up-or-in-flow.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/user-management/user-management.component.spec.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/user-management/user-management.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/user-profile/user-profile.component.ts
- packages/sdks/react-sdk/src/components/AccessKeyManagement.tsx
- packages/sdks/react-sdk/src/components/ApplicationsPortal.tsx
- packages/sdks/react-sdk/src/components/AuditManagement.tsx
- packages/sdks/react-sdk/src/components/RoleManagement.tsx
- packages/sdks/react-sdk/src/components/UserManagement.tsx
- packages/sdks/react-sdk/src/components/UserProfile.tsx
- packages/sdks/react-sdk/src/types.ts
- packages/sdks/vue-sdk/src/AccessKeyManagement.vue
- packages/sdks/vue-sdk/src/ApplicationsPortal.vue
- packages/sdks/vue-sdk/src/AuditManagement.vue
https://github.com/descope/etc/issues/4875
https://github.com/descope/descope-js/pull/782
add style id to angular
add style id to all widgets in angular, vue and react
> feat: add style-id to widgets

- packages/libs/escape-markdown/project.json
- packages/sdks/core-js-sdk/src/constants/apiPaths.ts
- packages/sdks/core-js-sdk/src/sdk/flow/types.ts
- packages/sdks/core-js-sdk/src/sdk/index.ts
- packages/sdks/core-js-sdk/test/sdk/sdk.test.ts
- packages/sdks/react-sdk/test/hooks/useAuth.test.tsx
- packages/sdks/web-js-sdk/src/enhancers/withAutoRefresh/index.ts
- packages/sdks/web-js-sdk/src/enhancers/withLastLoggedInUser/index.ts
- packages/sdks/web-js-sdk/src/enhancers/withNotifications/index.ts
- packages/sdks/web-js-sdk/src/enhancers/withPersistTokens/index.ts
- packages/sdks/web-js-sdk/test/persistTokens.test.ts
- pnpm-lock.yaml
Reverts descope/descope-js#846
> Revert "feat: Logout previous sessions" RELEASE

- .github/workflows/release-next-react-sdk.yml
- packages/sdks/react-sdk/CHANGELOG.md
https://github.com/descope/etc/issues/8240
> chore: Fix react-sdk next version release

- packages/widgets/user-management-widget/src/lib/helpers.ts
- packages/widgets/user-management-widget/src/lib/widget/api/types.ts
- packages/widgets/user-management-widget/src/lib/widget/state/selectors.ts
Related https://github.com/descope/etc/issues/8330
| orch. service | [Link to PR](https://github.com/descope/orchestrationservice/pull/3042) |
Display formatted text in UserMgmt widget.
> feat: UserMgmt widget date format

- pnpm-lock.yaml
> fix: run pnpm

- packages/sdks/react-sdk/src/components/AccessKeyManagement.tsx
- packages/sdks/react-sdk/src/components/AuditManagement.tsx
- packages/sdks/react-sdk/src/components/RoleManagement.tsx
- packages/sdks/react-sdk/src/components/UserManagement.tsx
- packages/widgets/access-key-management-widget/src/lib/widget/mixins/apiMixin.ts
- packages/widgets/audit-management-widget/src/lib/widget/mixins/apiMixin.ts
- packages/widgets/role-management-widget/src/lib/widget/mixins/apiMixin.ts
- packages/widgets/user-management-widget/src/lib/widget/mixins/apiMixin.ts
Fixes https://github.com/descope/etc/issues/8808
> fix: Widgets tenant ID attribute RELEASE

- packages/sdks/react-sdk/src/components/Descope.tsx
- packages/sdks/web-component/src/lib/descope-wc/BaseDescopeWc.ts
> fix: tenant attr in Descope.js component RELEASE

- packages/libs/sdk-component-drivers/src/FlowDriver.ts
- packages/widgets/user-profile-widget/src/app/index.html
- packages/widgets/user-profile-widget/src/lib/widget/mixins/flowSyncThemeMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initAvatarMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initEmailUserAttrMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initNameUserAttrMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initPasskeyUserAuthMethodMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initPasswordUserAuthMethodMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initPhoneUserAttrMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initUserCustomAttributesMixin.ts
Fixes https://github.com/descope/etc/issues/8959
> fix: Issue8959

- renovate.json
> chore: enable renovate

- packages/sdks/core-js-sdk/src/sdk/types.ts
fixes https://github.com/descope/etc/issues/9250
> fix: Add user password indication

- packages/sdks/nextjs-sdk/README.md
- packages/sdks/nextjs-sdk/examples/app-router/app/api/route.ts
- packages/sdks/nextjs-sdk/examples/app-router/app/page.tsx
- packages/sdks/nextjs-sdk/package.json
- packages/sdks/nextjs-sdk/src/server/session.ts
- packages/sdks/nextjs-sdk/test/server/session.test.ts
- pnpm-lock.yaml
Fixes https://github.com/descope/descope-js/issues/884
Adjust session function to be async
this is breaking changes, but works on next13/14 as well
I will bump major for this to version 1 (we are currently on 0...)
> fix: next 15

- .github/workflows/release-next-react-sdk.yml
- .github/workflows/release.yml
fix corepack set up in release ci
> fix(ci): corepack in RELEASE

- packages/sdks/react-sdk/src/types.ts
might fix https://github.com/descope/etc/issues/9400
adjust TS override
> fix: TS override

- packages/libs/sdk-mixins/src/mixins/configMixin/types.ts
- packages/sdks/web-component/src/lib/constants/customScreens.ts
- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/sdks/web-component/src/lib/helpers/conditions.ts
- packages/sdks/web-component/src/lib/helpers/templates.ts
- packages/sdks/web-component/src/lib/types.ts
- packages/sdks/web-component/test/descope-wc.test.ts
Related to https://github.com/descope/etc/issues/8207
Adds support for components' attributes via SDK
> feat: support components attributes

- packages/widgets/user-management-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initEditUserModalMixin.ts
Related to: https://github.com/descope/console-app/pull/3828
> fix: Add relevant names fields to user widget RELEASE

- packages/sdks/nextjs-sdk/CHANGELOG.md
- packages/sdks/nextjs-sdk/README.md
- packages/sdks/nextjs-sdk/examples/app-router/app/my-applications-portal/page.tsx
- packages/sdks/nextjs-sdk/src/server/authMiddleware.ts
- packages/sdks/nextjs-sdk/src/server/sdk.ts
- packages/sdks/nextjs-sdk/src/server/session.ts
- packages/sdks/nextjs-sdk/test/server/authMiddleware.test.ts
- packages/sdks/nextjs-sdk/test/server/session.test.ts
- pnpm-lock.yaml
Fixes https://github.com/descope/etc/issues/9622
make `session` to work also outside middleware, or of middleware was chained
> feat: Take cookie from session

- packages/sdks/nextjs-sdk/src/server/session.ts
- packages/sdks/web-js-sdk/src/enhancers/withNotifications/index.ts
add log to see if fallback happens and consider missing session expiration
> chore: add log and fix missing session expiration 

- packages/sdks/angular-sdk/README.md
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/descope/descope.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-in-flow/sign-in-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-in-flow/sign-in-flow.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-flow/sign-up-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-flow/sign-up-flow.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-or-in-flow/sign-up-or-in-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-or-in-flow/sign-up-or-in-flow.component.ts
- packages/sdks/react-sdk/README.md
- packages/sdks/react-sdk/src/components/Descope.tsx
- packages/sdks/react-sdk/src/types.ts
- packages/sdks/vue-sdk/README.md
- packages/sdks/vue-sdk/src/Descope.vue
- packages/sdks/web-component/README.md
- packages/sdks/web-component/src/lib/descope-wc/BaseDescopeWc.ts
- packages/sdks/web-component/test/descope-wc.test.ts
Related https://github.com/descope/etc/issues/2098
> fix: added nonce to sdks and update readme

- packages/sdks/angular-sdk/README.md
- packages/sdks/core-js-sdk/src/sdk/helpers/index.ts
- packages/sdks/core-js-sdk/src/sdk/index.ts
- packages/sdks/core-js-sdk/test/sdk/sdk.test.ts
- packages/sdks/nextjs-sdk/src/client/index.ts
- packages/sdks/nextjs-sdk/test/index.test.ts
- packages/sdks/react-sdk/README.md
- packages/sdks/react-sdk/src/flows.ts
- packages/sdks/react-sdk/src/sdk.ts
- packages/sdks/react-sdk/test/utilityFunctions.test.ts
- packages/sdks/vue-sdk/README.md
- packages/sdks/vue-sdk/src/index.ts
- packages/sdks/vue-sdk/src/sdk.ts
- packages/sdks/vue-sdk/tests/utilityFunctions.test.ts
Fixes https://github.com/descope/etc/issues/4901
add `getCurrentTenant` utility
> feat: get current tenant

- packages/sdks/angular-sdk/README.md
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/descope/descope.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-in-flow/sign-in-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-in-flow/sign-in-flow.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-flow/sign-up-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-flow/sign-up-flow.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-or-in-flow/sign-up-or-in-flow.component.html
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/sign-up-or-in-flow/sign-up-or-in-flow.component.ts
- packages/sdks/react-sdk/README.md
- packages/sdks/react-sdk/src/components/Descope.tsx
- packages/sdks/react-sdk/src/types.ts
- packages/sdks/vue-sdk/README.md
- packages/sdks/vue-sdk/src/Descope.vue
- packages/sdks/web-component/README.md
- packages/sdks/web-component/src/app/index.html
- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/sdks/web-component/src/lib/helpers/state.ts
- packages/sdks/web-component/src/lib/helpers/templates.ts
Fixes https://github.com/descope/etc/issues/8643
> feat: added option to dismiss screen error on input

- packages/sdks/nextjs-sdk/.eslintrc
- packages/sdks/nextjs-sdk/README.md
- packages/sdks/nextjs-sdk/src/server/authMiddleware.ts
- packages/sdks/nextjs-sdk/src/server/logger.ts
- packages/sdks/nextjs-sdk/src/server/session.ts
- packages/sdks/nextjs-sdk/src/types.ts
- packages/sdks/nextjs-sdk/test/server/logger.test.ts
Fixes https://github.com/descope/etc/issues/9670
added log level for next server API
> feat: next sdk log level

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Related https://github.com/descope/etc/issues/7376
> fix: Handle buttons by data-type RELEASE

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/sdks/web-component/src/lib/descope-wc/sdkScripts/grecaptcha.ts
- packages/sdks/web-component/src/lib/types.ts
- packages/sdks/web-component/test/sdkScripts/grecaptcha.test.ts
Fixes https://github.com/descope/etc/issues/9559
- Adding a token refresh mechanism to ensure valid tokens during form submission
- Implementing proper timeout handling to prevent UI blocking
> feat(client-scripts): add token refresh functionality

- packages/sdks/core-js-sdk/src/sdk/types.ts
https://github.com/descope/etc/issues/9848
Add SCIM attribute to user
> feat: Add SCIM attribute to user RELEASE

- packages/sdks/core-js-sdk/src/constants/apiPaths.ts
- packages/sdks/core-js-sdk/src/sdk/oauth/index.ts
- packages/sdks/core-js-sdk/src/sdk/types.ts
- packages/sdks/web-js-sdk/src/sdk/fedcm.ts
- packages/sdks/web-js-sdk/test/fedcm.test.ts
Fixes https://github.com/descope/etc/issues/9083
add exchangeProviderToken API and nonce generation to onetap
> feat: Add exchangeProviderToken API to onetap

- packages/widgets/access-key-management-widget/src/lib/widget/api/sdk/mocks.ts
- packages/widgets/audit-management-widget/src/lib/widget/api/sdk/mocks.ts
- packages/widgets/user-management-widget/src/lib/widget/api/sdk/mocks.ts
- packages/widgets/user-management-widget/src/lib/widget/api/types.ts
- packages/widgets/user-management-widget/src/lib/widget/state/selectors.ts
Fixes https://github.com/descope/etc/issues/9806
> fix: Add formatted time to widget mocks RELEASE

- packages/sdks/angular-sdk/package.json
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/services/descope-auth.service.ts
- packages/sdks/react-sdk/package.json
- packages/sdks/react-sdk/src/sdk.ts
- packages/sdks/vue-sdk/package.json
- packages/sdks/vue-sdk/src/hooks.ts
- packages/sdks/vue-sdk/src/plugin.ts
- packages/sdks/vue-sdk/src/sdk.ts
- pnpm-lock.yaml
fix oidc client TS issue by adding the package as dev dependency
> fix: fix oidc client TS issue

- packages/widgets/user-profile-widget/src/lib/widget/mixins/flowRedirectUrlMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/helpers.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initAvatarMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initEmailUserAttrMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initNameUserAttrMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initPasskeyUserAuthMethodMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initPasswordUserAuthMethodMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initPhoneUserAttrMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initTotpUserAuthMethodMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initUserCustomAttributesMixin.ts
Fixes https://github.com/descope/etc/issues/10037
> fix: issue 10037 RELEASE

- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/user-profile/user-profile.component.spec.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/user-profile/user-profile.component.ts
- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/services/descope-auth.service.ts
- packages/sdks/react-sdk/src/components/AuthProvider/AuthProvider.tsx
- packages/sdks/react-sdk/src/components/UserProfile.tsx
- packages/sdks/react-sdk/src/types.ts
- packages/sdks/react-sdk/test/components/DescopeWidgets.test.tsx
- packages/sdks/vue-sdk/src/UserProfile.vue
- packages/sdks/vue-sdk/src/plugin.ts
- packages/sdks/vue-sdk/src/types.ts
Fixes https://github.com/descope/etc/issues/10041
reseting state upon logout
missing vue
> fix: user profile handle logout

- packages/widgets/role-management-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initEditRolesButtonMixin.ts
- packages/widgets/role-management-widget/src/lib/widget/state/selectors.ts
Fixes https://github.com/descope/etc/issues/9220
> fix: Roles widget edit button RELEASE

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/sdks/web-component/src/lib/types.ts
related: https://github.com/descope/etc/issues/10083
> fix: open in new tab RELEASE

- packages/sdks/angular-sdk/projects/angular-sdk/src/lib/components/descope/descope.component.ts
Fixes https://github.com/descope/etc/issues/10142
> fix: issue 10142 RELEASE

- packages/libs/sdk-mixins/src/mixins/configMixin/types.ts
- packages/sdks/web-component/src/lib/helpers/conditions.ts
- packages/sdks/web-component/src/lib/types.ts
- packages/sdks/web-component/test/helpers/conditions.test.ts
fixes https://github.com/descope/etc/issues/10189
added few other conditions
> feat: more conditions

- packages/libs/sdk-mixins/src/mixins/staticResourcesMixin/fetchWithFallbacks.ts
Fixes https://github.com/descope/etc/issues/10171
> fix: retry when fetching resource throwing

- .github/workflows/release-next-react-sdk.yml
Release next version for all affected packages
> chore: next for all

- packages/sdks/core-js-sdk/src/sdk/types.ts
related to https://github.com/descope/etc/issues/10011
> feat: Add template ID and provider ID to update user requests

- packages/sdks/web-component/src/lib/helpers/helpers.ts
Fixes https://github.com/descope/etc/issues/8002
> fix: issue 8002 RELEASE

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/sdks/web-component/src/lib/helpers/state.ts
Fixes https://github.com/descope/etc/issues/10327
> fix: issue 10327 RELEASE

- packages/sdks/nextjs-sdk/README.md
- packages/sdks/nextjs-sdk/src/shared/AuthProvider.tsx
- packages/sdks/nextjs-sdk/test/shared/AuthProvider.test.tsx
Fixes https://github.com/descope/etc/issues/10426
change nextjs default cookie to samesite lax
> feat: change nextjs default cookie to samesite lax

- packages/sdks/core-js-sdk/src/httpClient/index.ts
- packages/sdks/core-js-sdk/test/httpClient.test.ts
- packages/sdks/web-js-sdk/test/persistTokens.test.ts
https://github.com/descope/etc/issues/10013
Add default project ID header to core
> feat: Add default project ID header to core

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
https://github.com/descope/etc/issues/9119
fix oauth race condition in case of closing window
> fix: oauth race condition

- packages/sdks/nextjs-sdk/CHANGELOG.md
- packages/sdks/nextjs-sdk/README.md
- packages/sdks/nextjs-sdk/src/server/authMiddleware.ts
- packages/sdks/nextjs-sdk/src/server/sdk.ts
- packages/sdks/nextjs-sdk/test/server/sdk.test.ts
Fixes https://github.com/descope/etc/issues/10602
use `NEXT_PUBLIC_DESCOPE_PROJECT_ID` and `NEXT_PUBLIC_DESCOPE_BASE_URL` where applicable, maintaining BC
> chore: improve next env vars

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Fixes https://github.com/descope/etc/issues/10689
> fix: issue 10689 RELEASE

- packages/libs/sdk-mixins/src/mixins/staticResourcesMixin/staticResourcesMixin.ts
- packages/widgets/access-key-management-widget/src/lib/widget/mixins/fetchWidgetPagesMixin.ts
Fixes: https://github.com/descope/etc/issues/11044
> fix: issue 11044 RELEASE

- packages/sdks/react-sdk/package.json
Fixes https://github.com/descope/etc/issues/11105
> fix: issue 11105 RELEASE

- packages/libs/sdk-component-drivers/src/UserAuthMethodDriver.ts
- packages/widgets/user-profile-widget/e2e/user-profile-widget.spec.ts
- packages/widgets/user-profile-widget/jest.config.js
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initPasskeyUserAuthMethodMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initPasswordUserAuthMethodMixin.ts
- packages/widgets/user-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initTotpUserAuthMethodMixin.ts
Related https://github.com/descope/etc/issues/11239
> feat: support passkey removal

- packages/widgets/applications-portal-widget/e2e/applications-portal-widget.spec.ts
- packages/widgets/applications-portal-widget/src/lib/widget/api/types.ts
- packages/widgets/applications-portal-widget/src/lib/widget/state/selectors.ts
- packages/widgets/applications-portal-widget/test/mocks/mockSsoApps.ts
Related https://github.com/descope/etc/issues/11400
> feat: APW - OIDC apps

- packages/widgets/tenant-profile-widget/src/lib/widget/mixins/initMixin/initComponentsMixins/initTenantSSOExclusionsMixin.ts
- packages/widgets/tenant-profile-widget/src/lib/widget/mixins/initMixin/initMixin.ts
- packages/widgets/tenant-profile-widget/src/lib/widget/state/selectors.ts
related to https://github.com/descope/etc/issues/11506
> feat: Support exclusion from sso by login ids

- packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
- packages/widgets/user-profile-widget/e2e/user-profile-widget.spec.ts
- packages/widgets/user-profile-widget/playwright.config.ts
Related https://github.com/descope/etc/issues/11567
> fix: trying to fix issue 11567 RELEASE

- packages/sdks/angular-sdk/projects/angular-sdk/src/environment.ts
- packages/widgets/access-key-management-widget/e2e/access-key-management-widget.spec.ts
- packages/widgets/access-key-management-widget/package.json
- packages/widgets/access-key-management-widget/playwright.config.ts
- packages/widgets/applications-portal-widget/e2e/applications-portal-widget.spec.ts
- packages/widgets/applications-portal-widget/package.json
- packages/widgets/applications-portal-widget/playwright.config.ts
- packages/widgets/audit-management-widget/e2e/audit-management-widget.spec.ts
- packages/widgets/audit-management-widget/package.json
- packages/widgets/audit-management-widget/playwright.config.ts
- packages/widgets/role-management-widget/e2e/role-management-widget.spec.ts
- packages/widgets/role-management-widget/package.json
- packages/widgets/role-management-widget/playwright.config.ts
- packages/widgets/tenant-profile-widget/e2e/tenant-profile-widget.spec.ts
- packages/widgets/tenant-profile-widget/package.json
- packages/widgets/tenant-profile-widget/playwright.config.ts
- packages/widgets/user-management-widget/e2e/user-management-widget.spec.ts
- packages/widgets/user-management-widget/package.json
- packages/widgets/user-management-widget/playwright.config.ts
- packages/widgets/user-profile-widget/e2e/user-profile-widget.spec.ts
- packages/widgets/user-profile-widget/package.json
- packages/widgets/user-profile-widget/playwright.config.ts
- pnpm-lock.yaml
> chore: Dynamic ports in widget playwright specs

- packages/sdks/core-js-sdk/src/sdk/outbound/index.ts
- packages/sdks/core-js-sdk/src/sdk/outbound/types.ts
- packages/sdks/core-js-sdk/test/sdk/outbound.test.ts
- pnpm-lock.yaml
Fixes https://github.com/descope/etc/issues/11785
Add tenantId and tenantLevel options to outbound connect method
> feat: Add tenant options to outbound connect. RELEASE

- packages/sdks/core-js-sdk/src/sdk/saml.ts
- packages/sdks/core-js-sdk/test/sdk/saml.test.ts
- packages/widgets/role-management-widget/playwright.config.ts
Add loginHint and forceAuthn to saml start
> feat: Add loginHint and forceAuthn to saml start RELEASE

- packages/sdks/angular-sdk/README.md
- packages/sdks/react-sdk/README.md
- packages/sdks/vue-sdk/README.md
- packages/sdks/web-js-sdk/README.md
- packages/sdks/web-js-sdk/src/enhancers/withPersistTokens/helpers.ts
- packages/sdks/web-js-sdk/src/enhancers/withPersistTokens/index.ts
- packages/sdks/web-js-sdk/src/enhancers/withPersistTokens/types.ts
- packages/sdks/web-js-sdk/test/persistTokens.test.ts
Fixes https://github.com/descope/etc/issues/12085
add cookie name to sessionTokenViaCookie
> feat: Add js cookiename
