descope/descope-js

packages/core-js-sdk/src/sdk/saml.ts, packages/core-js-sdk/test/sdk/saml.test.ts
https://github.com/descope/etc/issues/230
1. remove support of { redirect: boolean } config which should not be supported at this package as it used in JS
2. remove the type, (which didn't expose `tenantNameOrEmail` argument), as its not needed anymore
=> fix: improve saml response

packages/core-js-sdk/src/sdk/enchantedLink/types.ts, packages/core-js-sdk/src/sdk/otp/types.ts, packages/core-js-sdk/src/sdk/types.ts
this will fix https://github.com/descope/node-sdk/pull/184
the problem is that when the type is exported, the generated type cannot be inferred well
=> fix: use type locally instead of exported

packages/core-js-sdk/src/sdk/saml.ts, packages/core-js-sdk/test/sdk/saml.test.ts
Fixes [<link_to_github_issue>](https://github.com/descope/etc/issues/2543)
SSO supports either and email address or a tenant ID. Renamed the parameter to express that.
=> fix: Replace name with ID as it's expected

packages/web-component/src/lib/constants/index.ts, packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts, packages/web-component/src/lib/descope-wc/DescopeWc.ts, packages/web-component/src/lib/helpers/helpers.ts, packages/web-component/src/lib/types.ts, packages/web-component/test/descope-wc.test.ts
https://github.com/descope/etc/issues/310
When running flows in native Android, the final redirect cannot happen in the background, like happens with Enchanted links. This PR adds a new `redirect auth` URL parameter to know who the initiator is, and defers the redirect specifically for the case of background and android.
=> feat: Defer redirect when in background for Android

packages/web-component/src/lib/descope-wc/DescopeWc.ts, packages/web-component/test/descope-wc.test.ts
Fix duplicate redirect calls (one is canceled by the browser) caused by "update" event which triggered the callback once again.
Fixed by validating that values (effected the redirect) are really changed
=> Fix: duplicate redirect calls (one is canceled by the browser)

packages/core-js-sdk/src/sdk/types.ts
https://github.com/descope/etc/issues/4052
- add custom attributes field (though Descope support only string | boolean | number, I think `any` will make more sense in the long run)
- fix  totp/smal/oauth(TypeScript definition) to actual values (TOTP/SAML/OAuth)
=> fix: Add custom attributes

packages/web-component/src/lib/descope-wc/DescopeWc.ts, packages/web-component/src/lib/helpers/helpers.ts, packages/web-component/src/lib/helpers/webauthn.ts, packages/web-component/test/descope-wc.test.ts, packages/web-component/test/helpers/webauthn.test.ts
- Change WebAuthn `...Finish` actions to return the `failure` string instead of `cancelWebauthn` flag.
- Fixed issue where `getChromiumVersion` wasn't actually a function
- This caused Passkey Autofill to sometimes fail initialization in the console runner
- Updated the tests to hopefully cover all scenarios around this
=> chore: Add WebAuthn failure reason and fix autofill bug in getChromiumVersion

packages/web-js-sdk/README.md, packages/web-js-sdk/src/constants.ts, packages/web-js-sdk/src/enhancers/withAutoRefresh/index.ts, packages/web-js-sdk/test/autoRefresh.test.ts, packages/web-js-sdk/test/testUtils.ts
Fixes https://github.com/descope/etc/issues/4292
when session expiration is above 24.8 days - setTimeout will fire immediately - resulting a loop of refresh where eventually it will result 429
see more details in https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value
the solution here is to limit upper session with that upper bound 
here is where session expiration is 30 days
=> fix: large session expiration consideration 

packages/core-js-sdk/src/sdk/oauth/index.ts, packages/core-js-sdk/src/sdk/oauth/types.ts, packages/core-js-sdk/test/sdk/oauth.test.ts
Related to https://github.com/descope/etc/issues/4097
Support the ability to set any oauth provider and not only the default ones from a close list. 
This solution supports also backwards for existing usages
=> feat: support also custom oauth providers

packages/core-js-sdk/src/createSdk.ts, packages/core-js-sdk/src/httpClient/index.ts, packages/core-js-sdk/src/httpClient/types.ts, packages/core-js-sdk/test/httpClient.test.ts
* On Cloudflare, the `fetch` implementation does not support `credentials`. In this library, we create an http client using a `cookiePolicy` option that is then passed to `fetch`.
* This change allows the caller to pass `cookiePolicy: null` to `createHttpClient`, which will omit the `credentials` option when calling `fetch`. If null is not passed, the previous behavior is preserved.
* See https://github.com/cloudflare/workerd/blob/main/src/workerd/api/http.h#L591 for details on why Cloudflare will not implement `credentials` in their version of `fetch`.
Fixes #338
=> feat: allow caller to omit cookiePolicy

packages/web-component/src/lib/descope-wc/DescopeWc.ts, packages/web-component/test/descope-wc.test.ts
Fixes https://github.com/descope/etc/issues/3844
(instead of https://github.com/descope/descope-js/pull/257)
changing the mechanism to timeout based rather then interval based
tested "short polling" (screen/end after polling) and "long polling" (connector action with 2 secs timeout) on both EL and ML
=> fix: change polling to timeout

packages/libs/sdk-mixins/src/mixins/debuggerMixin/debugger-wc.ts, packages/web-component/src/app/index.html, packages/web-component/src/lib/debugger-wc.ts, packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts, packages/web-component/test/debugger.test.ts
related: https://github.com/descope/etc/issues/5847
I changed the loading order, now the theme is fetched without waiting for the config
should be slightly better but I don't see how we can improve it a lot by changing the code
2 points to take in consideration:
- Their login flow do not have the first page optimization
- We are preventing browser cache for static.descope resources
=> chore: trying to improve flow loading time

packages/core-js-sdk/src/httpClient/urlBuilder.ts, packages/core-js-sdk/test/httpClient.test.ts
Fixes https://github.com/descope/etc/issues/6428
The React-Native runtime doesn't support most of the `URL` and `URLSearchParams` fields and functionality.
The URL building function was replaced with a string-based approach supported by all.
=> fix: Replace URL building with string based operations

packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts
Related https://github.com/descope/etc/issues/6490
component context now using the latest values received from the components
=> fix: component context override order

packages/libs/sdk-mixins/src/mixins/staticResourcesMixin/staticResourcesMixin.ts, packages/web-component/src/lib/descope-wc/BaseDescopeWc.ts, packages/web-component/src/lib/descope-wc/DescopeWc.ts, packages/web-component/src/lib/helpers/helpers.ts, packages/web-component/test/descope-wc.test.ts
=> fix: add base-static-url param RELEASE

packages/web-js-sdk/package.json, packages/web-js-sdk/src/enhancers/withAutoRefresh/helpers.ts, packages/web-js-sdk/src/enhancers/withAutoRefresh/index.ts, packages/web-js-sdk/test/autoRefresh.test.ts, pnpm-lock.yaml
Fixes https://github.com/descope/etc/issues/6620
1. use jwt-decode to decode jwt (we already use it on core-js , same version, so no addition of deps)
2. gracefully handle a case where jwt decoding fails (just to be on the safe side)
=> fix: fix jwt decode on auto-refresh

packages/web-js-sdk/src/enhancers/withAutoRefresh/index.ts, packages/web-js-sdk/test/autoRefresh.test.ts
Fixes https://github.com/descope/etc/issues/6264
when token rotation applies, with multiple tabs
the problem with current solution is that it relies on the fact that `persistTokens` is supplied as well, hence this may break current behvior when someone using `autoRefresh: true` and `persistTokens: false` (which is not likely, but still)
@nirgur I would love to brainstorm on this topic with you
=> fix: make auto refresh to not use the request refresh

packages/core-js-sdk/src/constants/index.ts, packages/core-js-sdk/src/sdk/helpers/index.ts, packages/core-js-sdk/test/sdk/sdk.test.ts
get auth claims by current tenant for `getJwtPermissions` and `getJwtRoles`
with the following sample code
and the following jwt
here is the result
=> feat: get auth claims by current tenant if it matches

packages/web-component/src/lib/descope-wc/DescopeWc.ts
=> fix: validate all inputs on submit RELEASE

packages/core-js-sdk/src/createSdk.ts
https://github.com/descope/etc/issues/6918
Added an empty check for after request hooks for old react-native. It will throw otherwise.
=> fix: Add an explicit empty check in after request for old react native

packages/sdks/web-component/src/lib/descope-wc/BaseDescopeWc.ts, packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Fixes https://github.com/descope/etc/issues/7089
- Add a polling retry mechanism
- Also fixes an issue created by https://github.com/descope/descope-js/pull/736 where the state moved from the base to the  wc but the update did not move. It now completely resides in the WC level
=> fix: Fix poll errors RELEASE

packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Fix a case when click is response t triggers another polling
tested ML and EL with short and long polling
=> fix: polling timeout when click is response t triggers another polling

packages/sdks/react-sdk/src/components/AuthProvider/AuthProvider.tsx, packages/sdks/react-sdk/src/hooks/useUser.ts, packages/sdks/react-sdk/src/types.ts, packages/sdks/react-sdk/test/components/App.test.tsx
Fixes https://github.com/descope/etc/issues/7260
fix multiple fetch user when `useUser` happen multiple times
1. add ref on auth provider
2. consider that ref in hook
(this is similar to to approach that we have in `useSession`)
=> fix: fix multiple fetch user

packages/sdks/nextjs-sdk/README.md, packages/sdks/nextjs-sdk/src/server/authMiddleware.ts, packages/sdks/nextjs-sdk/test/server/authMiddleware.test.ts
Allow Descoper to define private routes as well as public ones, for sites that are majority public, but have specific private routes.
=> feat: Added Private Routes to Next JS SDK

packages/sdks/core-js-sdk/src/httpClient/urlBuilder.ts, packages/sdks/core-js-sdk/test/httpClient.test.ts
Fixes https://github.com/descope/etc/issues/7604
- Fix regression with encoding parameters
=> fix: Regression with encoding parameters

packages/sdks/core-js-sdk/src/index.ts, packages/sdks/core-js-sdk/src/sdk/types.ts, packages/sdks/core-js-sdk/src/sdk/webauthn.ts, packages/sdks/core-js-sdk/test/sdk/webauthn.test.ts, packages/sdks/web-js-sdk/src/sdk/webauthn.ts, packages/sdks/web-js-sdk/src/types.ts
Fixes https://github.com/descope/etc/issues/7847
Add optional passkeyOptions to all WebAuthn start calls
=> feat: Add passkeyOptions to all webauthn start calls

packages/sdks/core-js-sdk/src/sdk/types.ts, packages/sdks/core-js-sdk/test/sdk/enchantedLink.test.ts, packages/sdks/core-js-sdk/test/sdk/otp.test.ts
- Add support for `templateId` in `LoginOptions` and `SignUpOptions`
=> feat: Add support for templateId in LoginOptions and SignUpOptions

packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts
Fixes https://github.com/descope/etc/issues/8031
- This PR adds a hard timeout of `6 seconds` on the calls to `/next` in the enchanted link polling loop.
- This ensures that the polling always recovers after a reasonable time if network requests hang for whatever reason – bad routing, dropped packets, throttling (see below).
- It also adds a mechanism for detecting network request throttling in mobile Safari on iOS devices, possibly only on iOS 18 devices, to fail the poll early and retry as soon as possible.
When the flow is running in mobile Safari and the app is in the background, the `this.#pollingTimeout = setTimeout(...)` callback is not executed until the app returns to the foreground, but the network request that's executed straight after hangs for anywhere between 20-50 seconds. …
=> fix: Add longish timeout for polling calls and a shorter one when detecting iOS throttling RELEASE

packages/sdks/nextjs-sdk/package.json, packages/sdks/nextjs-sdk/rollup.config.js, pnpm-lock.yaml
Fixes https://github.com/descope/etc/issues/7785
add build aliases that convert 
tested on next13/14 both app router and pages router
=> fix: support next build for app router without transpile   

packages/libs/escape-markdown/project.json
=> fix: Remove LicenseCollector from EscapeMarkdown

packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts, packages/sdks/web-component/test/descope-wc.test.ts
https://github.com/descope/etc/issues/5992
Move native mobile resume logic into web-component sdk, both for Magic Link and OAuth
=> feat: Add nativeResume function and have polling check the current action

packages/libs/escape-markdown/project.json, packages/sdks/core-js-sdk/src/constants/apiPaths.ts, packages/sdks/core-js-sdk/src/sdk/flow/types.ts, packages/sdks/core-js-sdk/src/sdk/index.ts, packages/sdks/core-js-sdk/test/sdk/sdk.test.ts, packages/sdks/react-sdk/test/hooks/useAuth.test.tsx, packages/sdks/web-js-sdk/src/enhancers/withAutoRefresh/index.ts, packages/sdks/web-js-sdk/src/enhancers/withLastLoggedInUser/index.ts, packages/sdks/web-js-sdk/src/enhancers/withNotifications/index.ts, packages/sdks/web-js-sdk/src/enhancers/withPersistTokens/index.ts, packages/sdks/web-js-sdk/test/persistTokens.test.ts, pnpm-lock.yaml
https://github.com/descope/etc/issues/8242
Logout previous sessions
=> feat: Logout previous sessions RELEASE

packages/sdks/core-js-sdk/src/sdk/types.ts, packages/sdks/core-js-sdk/test/sdk/otp.test.ts
https://github.com/descope/etc/issues/8242
Add the revokeOtherSessions attribute in LoginOptions.
=> feat: Add the revokeOtherSessions attribute in LoginOptions RELEASE

packages/sdks/react-sdk/package.json
=> chore: marked react sdk as side effects free

packages/libs/sdk-mixins/src/mixins/descopeUiMixin/descopeUiMixin.ts, packages/sdks/web-component/rollup.config.app.mjs, packages/sdks/web-component/rollup.config.app.serve.mjs, packages/sdks/web-component/src/app/index.html
Fixes https://github.com/descope/etc/issues/9009
Adding a way to customize CDN
=> feat(web-component): add base-cdn-url attribute

.github/workflows/ci.yml, .github/workflows/pull_request.yml, .github/workflows/release-next-react-sdk.yml, .github/workflows/release.yml, package.json, pnpm-lock.yaml
moving pnpm and engine version away from ci yamo and to package.json
=> chore(ci): use corepack and engines

packages/sdks/nextjs-sdk/README.md
improve readme base on feedback
=> fix: next.js readme

packages/sdks/nextjs-sdk/README.md, packages/sdks/web-js-sdk/src/constants.ts, packages/sdks/web-js-sdk/src/enhancers/withAutoRefresh/helpers.ts, packages/sdks/web-js-sdk/src/enhancers/withAutoRefresh/index.ts, packages/sdks/web-js-sdk/test/autoRefresh.test.ts
Fixes https://github.com/descope/etc/issues/8912
Fixes https://github.com/descope/etc/issues/7424
handle too close timeouts in the following ways
- after auth request - if calculated timeout is less than 20 seconds - do not set refresh timeout
- when window becomes visible - do not refresh if refresh failed
=> fix: short timeout

packages/sdks/core-js-sdk/src/sdk/webauthn.ts, packages/sdks/core-js-sdk/test/sdk/webauthn.test.ts, packages/sdks/web-js-sdk/src/sdk/webauthn.ts
Fixes https://github.com/descope/etc/issues/9893
allow empty token on webauthn update
=> fix: allow empty token on webauthn update

packages/sdks/web-js-sdk/src/sdk/oidc/index.ts
Fixes https://github.com/descope/descope-js/issues/1070
from experimenting - it seems that require works better in this case, since bundlers don’t try to statically analyze require calls in the same way they do for import statements,
=> fix: OIDC client ts

packages/sdks/core-js-sdk/src/constants/apiPaths.ts, packages/sdks/core-js-sdk/src/sdk/index.ts, packages/sdks/core-js-sdk/src/sdk/outbound/index.ts, packages/sdks/core-js-sdk/src/sdk/outbound/types.ts, packages/sdks/core-js-sdk/src/sdk/outbound/validations.ts, packages/sdks/core-js-sdk/test/sdk/outbound.test.ts
Related to https://docs.descope.com/api/management/users/update-user-login-id
Support outbound app connect API in SDK
The request requires the user to be authenticated
The request variables are:
- `appId` (required)
- `options` object containing `redirectUrl` and `scopes` (optional)
- `token` (optional) as a string and will be used from the cookie
=> feat: outbound connect api

packages/sdks/angular-sdk/package.json, packages/sdks/nextjs-sdk/package.json, pnpm-lock.yaml
fixes https://github.com/descope/etc/issues/10088
remove engines declarations from next/angular sdks
testing
=> fix: remove engines declarations

packages/sdks/react-sdk/examples/app/index.tsx, packages/sdks/react-sdk/src/components/AuthProvider/AuthProvider.tsx
Fixes https://github.com/descope/etc/issues/10442
https://github.com/descope/descope-js/pull/1014
add `baseCdnUrl` prop to `<AuthProvider />` component
=> fix: add base cdn url to react sdk

packages/sdks/core-js-sdk/src/sdk/oauth/index.ts, packages/sdks/core-js-sdk/test/sdk/oauth.test.ts
fixes: https://github.com/descope/etc/issues/9752
fixes: https://github.com/descope/etc/issues/10809
Add login hint support for OAuth
=> feat: Add login hint support for OAuth

packages/sdks/react-sdk/README.md
Reverted message back to show support for React 16 with React SDK.
=> Fix: Fixed README to say we support React 16

packages/sdks/core-js-sdk/src/httpClient/helpers/createFetchLogger.ts, packages/sdks/core-js-sdk/test/httpClient.test.ts
Fixes https://github.com/descope/etc/issues/11222
Added a retry mechanism for handling specific HTTP status codes (`521` and `524`) by retrying the request once
=> fix: Issue 11222 - retry on 521 and 524

packages/sdks/nextjs-sdk/CHANGELOG.md, packages/sdks/nextjs-sdk/src/server/sdk.ts, packages/sdks/nextjs-sdk/test/server/sdk.test.ts
Fixes https://github.com/descope/etc/issues/11294
some context
the `getGlobalSdk` is used in 2 places
- in middleware - for session validation
- in `session` function - for session validation as well
we want to enable developer to pass different global sdks in this context
noting that at the moment, we don't let changing the base URL, I don't think there is such use case at the moment, but we can add this easily after this
this PR is still missing:
- tests
- maybe add a note in readme
=> feat: Support multiple global sdks in next sdk

packages/sdks/core-js-sdk/src/sdk/types.ts, packages/sdks/web-component/src/lib/constants/index.ts, packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts, packages/sdks/web-component/src/lib/helpers/helpers.ts, packages/sdks/web-component/src/lib/types.ts, packages/sdks/web-component/test/descope-wc.test.ts, packages/sdks/web-component/test/helpers/index.test.ts, packages/sdks/web-js-sdk/src/sdk/flow.ts, packages/sdks/web-js-sdk/test/sdk.test.ts
Related https://github.com/descope/etc/issues/11683
Adds oidcResource parameter support across Descope JS SDK packages for OIDC resource specification in authentication flows.
=> feat: add oidcResource parameter to SDK start options

packages/sdks/web-component/src/lib/descope-wc/DescopeWc.ts, packages/sdks/web-component/src/lib/helpers/helpers.ts
Fixes https://github.com/descope/etc/issues/12037
https://github.com/user-attachments/assets/7e93e85b-98b2-4a38-93b8-0e645e9e7f5b
Ensure popup is opened to communicate with broadcast channel, and the inject URL to it.
In case of inactivity (e.g. Cancel from the native UI) - poll to see if popup should be closed.
=> fix: Ensure popup for Apple OAuth on Mac Safari RELEASE

packages/sdks/react-sdk/README.md, packages/sdks/react-sdk/src/components/AuthProvider/useSdk.ts, packages/sdks/react-sdk/test/components/AuthProvider.test.tsx
Fixes https://github.com/descope/etc/issues/11965
When using the React SDK through Next.js there's an edge case that can
cause the `useMemo` in packages/sdks/react-sdk/src/components/AuthProvider/useSdk.ts 
to fail and create another SDK instance mid-operation, losing state.
=> fix(react-sdk/AuthProvider): workaround Next.js serialization when sessionTokenViaCookie = {} RELEASE
